---
- name: debian | adding haproxy ppa
  apt_repository:
    repo: "{{ haproxy_debian_repo }}"
    state: present
    update_cache: true
  become: true
  when: ansible_distribution == "Ubuntu"

- name: debian | installing haproxy and socat
  apt:
    name: ['haproxy', 'hatop', 'socat']
    state: present
  become: true

- name: debian | ensuring haproxy is enabled
  service:
    name: haproxy
    enabled: true
  become: true
  when: not ansible_check_mode
