---
- name: debian | adding haproxy ppa
  apt_repository:
    repo: "{{ haproxy_debian_repo }}"
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: debian | installing haproxy and socat
  apt:
    name:
      - haproxy
      - hatop
      - socat
    state: present
  become: true
  register: result
  until: result is successful
