---
# tasks file for ansible-haproxy
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: opensuse.yml
  when: ansible_os_family == "openSUSE Leap"

- include_tasks: service.yml

- name: Debug HAProxy SSL
  debug:
    var: haproxy_load_balancer_ssl

- include_tasks: ssl.yml
  when:
    - haproxy_load_balancer_ssl is defined
    - haproxy_load_balancer_ssl != []
    - haproxy_load_balancer_ssl.enabled|bool

- include_tasks: config_haproxy.yml
  when:
    - haproxy_config is defined
    - haproxy_config|bool

- name: Allowing Running HAProxy Instances To Bind To A VIP For Failover
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    state: present
    reload: yes
  become: true
