---
- name: opensuse | installing haproxy and socat
  zypper:
    name: ['haproxy', 'hatop', 'socat']
    state: present
  become: true

- name: opensuse | ensuring haproxy is enabled
  service:
    name: haproxy
    enabled: true
  become: true
  when: not ansible_check_mode
