---
- name: redhat | installing haproxy and socat
  yum:
    name: ['haproxy', 'socat']
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | installing haproxy and socat
  dnf:
    name: ['haproxy', 'socat']
    state: present
  become: true
  when: ansible_distribution == "Fedora"

- name: redhat | ensuring haproxy is enabled
  service:
    name: haproxy
    enabled: true
  become: true
  when: not ansible_check_mode
